@startuml

' Definir pacotes conforme o padrão MVC
package "Model" {
  class Cliente
  class Agente
  class Banco
  class PedidoAluguel
  class Automovel
  class ContratoCredito
}

package "View" {
  class AluguelView
  class PedidoView
  class ContratoView
}

package "Controller" {
  class ClienteController
  class PedidoController
  class ContratoController
}

Cliente --> ClienteController : "gerencia"
Agente --> ClienteController : "analisando"
Agente --> PedidoController : "registrando"
Banco --> ContratoController : "associando"

ClienteController --> AluguelView : "atualiza"
PedidoController --> PedidoView : "atualiza"
ContratoController --> ContratoView : "atualiza"


ClienteController --> PedidoAluguel : "manipula"
PedidoController --> Automovel : "manipula"
ContratoController --> ContratoCredito : "manipula"

@enduml
